import type { DomainData } from "./types";

export const demoIds = {
  facility: "facility-queen-care",
  assessment: "assessment-queen-care",
  room: "room-waiting",
  profile: "profile-walker",
  route: "route-entry-consultation",
  balancedScenario: "scenario-balanced",
} as const;

export const mockData: DomainData = {
  facilities: {
    [demoIds.facility]: {
      id: demoIds.facility,
      name: "Queen Care Clinic",
      address: "18 Queen's Road Central, Hong Kong",
      timezone: "Asia/Hong_Kong",
    },
  },
  assessments: {
    [demoIds.assessment]: {
      id: demoIds.assessment,
      facilityId: demoIds.facility,
      name: "Waiting Area & Consultation Corridor Safety Review",
      areaName: "Waiting Area and Consultation Corridor",
      status: "analysis-complete",
      step: "analysis",
      owner: "Maya Chen",
      updatedAt: "2026-09-27T10:30:00+08:00",
      riskScore: 68,
      roomIds: [demoIds.room],
      profileIds: [demoIds.profile],
      routeIds: [demoIds.route],
      hazardIds: ["hazard-chair", "hazard-corner", "hazard-light", "hazard-rail"],
      scenarioIds: ["scenario-current", "scenario-minimum", demoIds.balancedScenario, "scenario-safety"],
      selectedScenarioId: demoIds.balancedScenario,
      version: 3,
    },
  },
  rooms: {
    [demoIds.room]: {
      id: demoIds.room,
      name: "Waiting Area and Consultation Corridor",
      widthCm: 800,
      lengthCm: 600,
      wallThicknessCm: 14,
      origin: { x: 0, y: 0 },
    },
  },
  furniture: {
    "chair-a": {
      id: "chair-a",
      roomId: demoIds.room,
      name: "Waiting chair A",
      kind: "chair",
      position: { x: 235, y: 235 },
      widthCm: 52,
      depthCm: 52,
      rotationDeg: 0,
      movable: true,
    },
    "chair-b": {
      id: "chair-b",
      roomId: demoIds.room,
      name: "Waiting chair B",
      kind: "chair",
      position: { x: 295, y: 235 },
      widthCm: 52,
      depthCm: 52,
      rotationDeg: 0,
      movable: true,
    },
    "reception-desk": {
      id: "reception-desk",
      roomId: demoIds.room,
      name: "Reception desk",
      kind: "desk",
      position: { x: 520, y: 100 },
      widthCm: 180,
      depthCm: 70,
      rotationDeg: 0,
      movable: false,
    },
  },
  profiles: {
    [demoIds.profile]: {
      id: demoIds.profile,
      name: "Older adult using walker",
      description: "Mobility aid requiring 90 cm minimum route clearance and 150 cm turning circle.",
      minimumClearanceCm: 90,
      turningDiameterCm: 150,
      verified: true,
    },
  },
  routes: {
    [demoIds.route]: {
      id: demoIds.route,
      name: "Entrance → Reception → Waiting Seat → Consultation Room",
      roomId: demoIds.room,
      points: [
        { x: 50, y: 240 },
        { x: 150, y: 240 },
        { x: 290, y: 190 },
        { x: 450, y: 440 },
        { x: 700, y: 490 },
      ],
      profileIds: [demoIds.profile],
      critical: true,
    },
  },
  hazards: {
    "hazard-chair": {
      id: "hazard-chair",
      roomId: demoIds.room,
      title: "Waiting chair obstructing the route",
      description: "Waiting chair A narrows walker clearance to 54 cm.",
      severity: "critical",
      position: { x: 260, y: 235 },
      affectedProfileIds: [demoIds.profile],
      measuredClearanceCm: 54,
      requiredClearanceCm: 90,
      confidence: 0.96,
      recommendation: "Move Chairs A & B 60 cm against west wall.",
    },
    "hazard-corner": {
      id: "hazard-corner",
      roomId: demoIds.room,
      title: "Sharp furniture corner close to route",
      description: "Turning envelope overlaps magazine table corner.",
      severity: "high",
      position: { x: 400, y: 170 },
      affectedProfileIds: [demoIds.profile],
      measuredClearanceCm: 68,
      requiredClearanceCm: 90,
      confidence: 0.91,
      recommendation: "Install rounded edge protector.",
    },
    "hazard-light": {
      id: "hazard-light",
      roomId: demoIds.room,
      title: "Poor lighting near doorway",
      description: "Doorway threshold measures 85 lux, below 200 lux standard.",
      severity: "medium",
      position: { x: 450, y: 330 },
      affectedProfileIds: [demoIds.profile],
      measuredClearanceCm: 90,
      requiredClearanceCm: 90,
      confidence: 0.88,
      recommendation: "Install diffuse 200 lux LED luminaire.",
    },
    "hazard-rail": {
      id: "hazard-rail",
      roomId: demoIds.room,
      title: "2.1-metre route section without stable support",
      description: "Corridor run lacks grab rail or architectural hand support.",
      severity: "medium",
      position: { x: 450, y: 440 },
      affectedProfileIds: [demoIds.profile],
      measuredClearanceCm: 90,
      requiredClearanceCm: 90,
      confidence: 0.85,
      recommendation: "Mount 1.8 m continuous architectural handrail.",
    },
  },
  scenarios: {
    "scenario-current": {
      id: "scenario-current",
      name: "Current layout",
      objective: "Baseline",
      riskScore: 68,
      estimatedCostHkd: 0,
      effort: "low",
      disruption: "low",
      changes: [],
    },
    "scenario-minimum": {
      id: "scenario-minimum",
      name: "Minimum cost",
      objective: "Eliminate critical blockage without purchases",
      riskScore: 39,
      estimatedCostHkd: 0,
      effort: "low",
      disruption: "low",
      changes: [{ furnitureId: "chair-a", from: { x: 235, y: 235 }, to: { x: 80, y: 160 }, note: "Move chair away from route." }],
    },
    [demoIds.balancedScenario]: {
      id: demoIds.balancedScenario,
      name: "Balanced",
      objective: "Best safety-to-cost ratio for walker transit",
      riskScore: 27,
      estimatedCostHkd: 850,
      effort: "medium",
      disruption: "low",
      changes: [
        { furnitureId: "chair-a", from: { x: 235, y: 235 }, to: { x: 80, y: 160 }, note: "Move chair to perimeter." },
        { furnitureId: "chair-b", from: { x: 295, y: 235 }, to: { x: 140, y: 160 }, note: "Move chair to perimeter." },
      ],
    },
    "scenario-safety": {
      id: "scenario-safety",
      name: "Maximum safety",
      objective: "Maximize route and turning clearance",
      riskScore: 18,
      estimatedCostHkd: 3200,
      effort: "high",
      disruption: "medium",
      changes: [
        { furnitureId: "chair-a", from: { x: 235, y: 235 }, to: { x: 80, y: 160 }, note: "Relocate seating bank." },
      ],
    },
  },
  reviews: {
    "review-queen-care": {
      id: "review-queen-care",
      assessmentId: demoIds.assessment,
      reviewer: "Dr. Adrian Lau",
      role: "Registered Occupational Therapist, HKROT",
      status: "pending",
      dueAt: "2026-09-29T17:00:00+08:00",
    },
  },
  reports: {
    "report-queen-care": {
      id: "report-queen-care",
      assessmentId: demoIds.assessment,
      audience: "facility-manager",
      openRiskIds: [],
      disclaimer: "SafeSpace clinical decision-support assessment. Verify dimensions on site.",
    },
  },
};
